"""Generates synthetic (battle_graph, label) pairs to train TrafficGAT.

Labels come from a hand-authored ground-truth function that is
DELIBERATELY DIFFERENT from traffic_engine.py's deterministic formula --
training and evaluating the GNN against labels generated by the same logic
as the thing it's supposed to beat would make the ablation test circular
and worthless. This ground-truth function models the same real-world
factors (rear pressure, tow effects, blockage risk) but combines them with
different weights and a couple of interaction terms the deterministic
baseline doesn't capture (e.g. defensive_likelihood x nearby-car-count
interaction, modeling that a defensive rival is more dangerous specifically
when they have cars to hide behind) -- this is the kind of relational
pattern a graph model has a *chance* of learning that a flat deterministic
formula structurally can't, which is the entire premise being tested.
"""

import csv
import random
from pathlib import Path

from app.schemas.telemetry import (
    DecisionRequest, EgoState, TargetState, TrafficState, TrackState, RulesState,
)
from app.schemas.common import DecisionMode
from app.models.rival_estimator import estimate as estimate_rival
from app.models.battle_graph import build_battle_graph

OUTPUT_PATH = Path(__file__).resolve().parents[1] / "app" / "data" / "training" / "battle_graph_windows.csv"


def _random_request(rng: random.Random, request_id: str, sparse_prob: float = 0.25) -> DecisionRequest:
    # Deliberately oversample sparse/isolated-style graphs (large rear gap,
    # large post-pass gap, few nearby cars, all *together* -- not just each
    # dimension independently). Uniform sampling of each field separately
    # makes the joint "everything is clear" case rare even when each
    # individual range technically covers it, which is exactly why the GNN
    # was never exposed to enough 2-3 node graphs during training and then
    # failed badly on scripts/ablation_test_gnn.py's simple_isolated_pass
    # category (-1235% vs. the baseline).
    if rng.random() < sparse_prob:
        rear_gap_s = rng.uniform(2.5, 4.5)
        post_pass_traffic_gap_s = rng.uniform(2.5, 4.5)
        cars_within_3s = rng.randint(0, 1)
    else:
        rear_gap_s = rng.uniform(0.15, 3.0)
        post_pass_traffic_gap_s = rng.uniform(0.2, 3.0)
        cars_within_3s = rng.randint(0, 6)

    return DecisionRequest(
        request_id=request_id, timestamp_ms=0, telemetry_age_ms=30,
        ego=EgoState(soc_pct=rng.uniform(20, 90), speed_kph=rng.uniform(180, 320),
                     throttle_pct=90, brake_pct=0, tyre_grip_estimate=rng.uniform(0.5, 0.95),
                     laps_remaining=rng.randint(1, 55), current_mode="HOLD"),
        target=TargetState(gap_s=rng.uniform(0.15, 2.0), relative_speed_kph=rng.uniform(-5, 30),
                            stint_age_laps=rng.randint(1, 40), recent_sector_delta_s=rng.gauss(0, 0.2)),
        traffic=TrafficState(rear_gap_s=rear_gap_s, cars_within_3s=cars_within_3s,
                              post_pass_traffic_gap_s=post_pass_traffic_gap_s),
        track=TrackState(track_id="synth", segment_type=rng.choice(["DRS_STRAIGHT", "CORNER"]),
                          drs_available=rng.random() < 0.6, straight_remaining_m=rng.uniform(150, 900),
                          braking_zone_m=rng.uniform(90, 160), overtake_difficulty=rng.uniform(0.2, 0.9)),
        rules=RulesState(deployment_budget_remaining_kj=rng.uniform(400, 2200),
                          minimum_reserve_soc_pct=rng.uniform(10, 20), full_deploy_allowed=True),
        decision_mode=DecisionMode.VERIFIED,
    )


def _ground_truth_labels(req: DecisionRequest, defensive_likelihood: float, rng: random.Random) -> dict:
    """Independent ground-truth formula -- see module docstring for why
    this must differ structurally from traffic_engine.py's."""
    traffic = req.traffic
    target = req.target

    tow = max(0.0, min(1.0, (1.3 - target.gap_s) * 0.55 + abs(target.relative_speed_kph) / 70.0))

    # Interaction term the deterministic baseline doesn't have: a defensive
    # rival is disproportionately more dangerous when they have nearby cars
    # to use as cover/blockers, not just additively more dangerous.
    density_interaction = defensive_likelihood * min(1.0, traffic.cars_within_3s / 4.0) * 0.4
    rear_pressure = max(0.0, 1.0 - traffic.rear_gap_s / 1.4)
    counterattack = max(0.0, min(1.0, 0.35 * rear_pressure + 0.25 * defensive_likelihood + density_interaction))

    blockage = max(0.0, min(1.0, 1.0 - traffic.post_pass_traffic_gap_s / 1.3))

    noise = lambda: rng.gauss(0, 0.05)
    return {
        "tow_strength": max(0.0, min(1.0, tow + noise())),
        "counterattack_risk": max(0.0, min(1.0, counterattack + noise())),
        "post_pass_traffic_risk": max(0.0, min(1.0, blockage + noise())),
    }


def generate_dataset(n: int = 4000, seed: int = 11):
    rng = random.Random(seed)
    rows = []
    for i in range(n):
        req = _random_request(rng, f"bg-{i}")
        rival = estimate_rival(req)
        graph = build_battle_graph(req, rival)
        labels = _ground_truth_labels(req, rival.defensive_likelihood, rng)

        rows.append({
            "request_id": req.request_id,
            "node_features": graph.node_features.tolist(),
            "edge_index": graph.edge_index.tolist(),
            "edge_features": graph.edge_features.tolist(),
            "node_mask": graph.node_mask.tolist(),
            "tow_strength": labels["tow_strength"],
            "counterattack_risk": labels["counterattack_risk"],
            "post_pass_traffic_risk": labels["post_pass_traffic_risk"],
        })
    return rows


def write_jsonl(rows: list[dict], path: Path = OUTPUT_PATH):
    import json
    path = path.with_suffix(".jsonl")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        for row in rows:
            f.write(json.dumps(row) + "\n")
    return path


if __name__ == "__main__":
    rows = generate_dataset()
    out_path = write_jsonl(rows)
    print(f"Wrote {len(rows)} synthetic battle-graph windows -> {out_path}")